services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: gintly_app

    ports:
      - "8000:80"

    env_file:
      - .env

    environment:
      APP_ENV: local
      APP_DEBUG: "true"

      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: gintly
      DB_USERNAME: gintly
      DB_PASSWORD: gintly_password

      cache_store: file
      session_driver: file
      queue_connection: sync

    depends_on:
      db:
        condition: service_healthy

    restart: unless-stopped


  db:
    image: mysql:8.0

    container_name: gintly_db

    environment:
      MYSQL_DATABASE: gintly
      MYSQL_USER: gintly
      MYSQL_PASSWORD: gintly_password
      MYSQL_ROOT_PASSWORD: root_password

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-proot_password"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped


volumes:
  mysql_data: